/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphical;

import static java.lang.System.exit;
import Code.*;
/**
 *
 * @author Aakash Bajaj
 */
public class Solver extends javax.swing.JFrame {

    
    public Integer[][] grid = new Integer[9][9];
    
    public static class GridClass{
        public Integer[][] ansgrid;

        public GridClass() {
            this.ansgrid = new Integer[9][9];
            int i,j;
            for(i=0;i<9;i++)
            for(j=0;j<9;j++)
            {
                this.ansgrid[i][j] = 0;
            }
        }
        };
    
    GridClass g1 = new GridClass();
    
    public Solver() {
        initComponents();
        int i,j;
        for(i=0;i<9;i++)
            for(j=0;j<9;j++)
            {
                grid[i][j] = 0;
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g11 = new javax.swing.JTextField();
        g12 = new javax.swing.JTextField();
        g13 = new javax.swing.JTextField();
        g14 = new javax.swing.JTextField();
        g15 = new javax.swing.JTextField();
        g16 = new javax.swing.JTextField();
        g17 = new javax.swing.JTextField();
        g18 = new javax.swing.JTextField();
        g19 = new javax.swing.JTextField();
        g21 = new javax.swing.JTextField();
        g22 = new javax.swing.JTextField();
        g23 = new javax.swing.JTextField();
        g24 = new javax.swing.JTextField();
        g25 = new javax.swing.JTextField();
        g26 = new javax.swing.JTextField();
        g27 = new javax.swing.JTextField();
        g28 = new javax.swing.JTextField();
        g29 = new javax.swing.JTextField();
        g31 = new javax.swing.JTextField();
        g32 = new javax.swing.JTextField();
        g33 = new javax.swing.JTextField();
        g34 = new javax.swing.JTextField();
        g35 = new javax.swing.JTextField();
        g36 = new javax.swing.JTextField();
        g37 = new javax.swing.JTextField();
        g38 = new javax.swing.JTextField();
        g39 = new javax.swing.JTextField();
        g41 = new javax.swing.JTextField();
        g42 = new javax.swing.JTextField();
        g43 = new javax.swing.JTextField();
        g44 = new javax.swing.JTextField();
        g45 = new javax.swing.JTextField();
        g46 = new javax.swing.JTextField();
        g47 = new javax.swing.JTextField();
        g48 = new javax.swing.JTextField();
        g49 = new javax.swing.JTextField();
        g51 = new javax.swing.JTextField();
        g52 = new javax.swing.JTextField();
        g53 = new javax.swing.JTextField();
        g54 = new javax.swing.JTextField();
        g55 = new javax.swing.JTextField();
        g56 = new javax.swing.JTextField();
        g57 = new javax.swing.JTextField();
        g58 = new javax.swing.JTextField();
        g59 = new javax.swing.JTextField();
        g61 = new javax.swing.JTextField();
        g62 = new javax.swing.JTextField();
        g63 = new javax.swing.JTextField();
        g64 = new javax.swing.JTextField();
        g65 = new javax.swing.JTextField();
        g66 = new javax.swing.JTextField();
        g67 = new javax.swing.JTextField();
        g68 = new javax.swing.JTextField();
        g69 = new javax.swing.JTextField();
        g71 = new javax.swing.JTextField();
        g72 = new javax.swing.JTextField();
        g73 = new javax.swing.JTextField();
        g74 = new javax.swing.JTextField();
        g75 = new javax.swing.JTextField();
        g76 = new javax.swing.JTextField();
        g77 = new javax.swing.JTextField();
        g78 = new javax.swing.JTextField();
        g79 = new javax.swing.JTextField();
        g81 = new javax.swing.JTextField();
        g82 = new javax.swing.JTextField();
        g83 = new javax.swing.JTextField();
        g84 = new javax.swing.JTextField();
        g85 = new javax.swing.JTextField();
        g86 = new javax.swing.JTextField();
        g87 = new javax.swing.JTextField();
        g88 = new javax.swing.JTextField();
        g89 = new javax.swing.JTextField();
        g91 = new javax.swing.JTextField();
        g92 = new javax.swing.JTextField();
        g93 = new javax.swing.JTextField();
        g94 = new javax.swing.JTextField();
        g95 = new javax.swing.JTextField();
        g96 = new javax.swing.JTextField();
        g97 = new javax.swing.JTextField();
        g98 = new javax.swing.JTextField();
        g99 = new javax.swing.JTextField();
        clearbtn = new javax.swing.JButton();
        solvebtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku Solver");

        g11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g14.setBackground(new java.awt.Color(153, 255, 255));
        g14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g15.setBackground(new java.awt.Color(153, 255, 255));
        g15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g16.setBackground(new java.awt.Color(153, 255, 255));
        g16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g16.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g17.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g18.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g19.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g21.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g23.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g23.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g24.setBackground(new java.awt.Color(153, 255, 255));
        g24.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g24.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g25.setBackground(new java.awt.Color(153, 255, 255));
        g25.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g25.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g26.setBackground(new java.awt.Color(153, 255, 255));
        g26.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g26ActionPerformed(evt);
            }
        });

        g27.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g27.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g28.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g28.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g29.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g29.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g31.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g31.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g32.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g32.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g33.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g33.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g34.setBackground(new java.awt.Color(153, 255, 255));
        g34.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g34.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g35.setBackground(new java.awt.Color(153, 255, 255));
        g35.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g35ActionPerformed(evt);
            }
        });

        g36.setBackground(new java.awt.Color(153, 255, 255));
        g36.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g36.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g37.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g37.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g38.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g38.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g39.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g39.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g41.setBackground(new java.awt.Color(153, 255, 255));
        g41.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g41.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g42.setBackground(new java.awt.Color(153, 255, 255));
        g42.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g42.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g43.setBackground(new java.awt.Color(153, 255, 255));
        g43.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g43.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g44.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g44.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g45.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g45.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g46.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g46.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g47.setBackground(new java.awt.Color(153, 255, 255));
        g47.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g47.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g48.setBackground(new java.awt.Color(153, 255, 255));
        g48.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g48.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g49.setBackground(new java.awt.Color(153, 255, 255));
        g49.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g49.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g51.setBackground(new java.awt.Color(153, 255, 255));
        g51.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g51.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g52.setBackground(new java.awt.Color(153, 255, 255));
        g52.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g52.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g53.setBackground(new java.awt.Color(153, 255, 255));
        g53.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g53.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g54.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g54.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g55.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g55.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g56.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g56.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g57.setBackground(new java.awt.Color(153, 255, 255));
        g57.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g57.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g58.setBackground(new java.awt.Color(153, 255, 255));
        g58.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g58.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g59.setBackground(new java.awt.Color(153, 255, 255));
        g59.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g59.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g61.setBackground(new java.awt.Color(153, 255, 255));
        g61.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g61.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g62.setBackground(new java.awt.Color(153, 255, 255));
        g62.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g62.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g63.setBackground(new java.awt.Color(153, 255, 255));
        g63.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g63.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g64.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g64.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g65.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g65.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g66.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g66.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g67.setBackground(new java.awt.Color(153, 255, 255));
        g67.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g67.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g68.setBackground(new java.awt.Color(153, 255, 255));
        g68.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g68.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g69.setBackground(new java.awt.Color(153, 255, 255));
        g69.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g69.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g71.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g71.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g72.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g72.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g73.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g73.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g74.setBackground(new java.awt.Color(153, 255, 255));
        g74.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g74.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g75.setBackground(new java.awt.Color(153, 255, 255));
        g75.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g75.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g76.setBackground(new java.awt.Color(153, 255, 255));
        g76.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g76.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g77.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g77.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g78.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g78.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g79.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g79.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g81.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g81.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g82.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g82.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g83.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g83.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g84.setBackground(new java.awt.Color(153, 255, 255));
        g84.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g84.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g85.setBackground(new java.awt.Color(153, 255, 255));
        g85.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g85.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g86.setBackground(new java.awt.Color(153, 255, 255));
        g86.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g86.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g87.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g87.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g88.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g88.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g89.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g89.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g91.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g91.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g92.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g92.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g93.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g93.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g94.setBackground(new java.awt.Color(153, 255, 255));
        g94.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g94.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g95.setBackground(new java.awt.Color(153, 255, 255));
        g95.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g95.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g96.setBackground(new java.awt.Color(153, 255, 255));
        g96.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g96.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g97.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g97.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g98.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g98.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        g99.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        g99.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        g99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g99ActionPerformed(evt);
            }
        });

        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        solvebtn.setText("Solve");
        solvebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solvebtnActionPerformed(evt);
            }
        });

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(g91, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g92, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g93, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(g81, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g82, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g83, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(g71, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g72, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g73, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(g61, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g62, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g63, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(g51, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g52, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g53, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(g41, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g42, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g43, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(g31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(g21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(g11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(g13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g34, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g35, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g36, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g37, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g38, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g39, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g28, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g64, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g65, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g66, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g54, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g55, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g56, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g44, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g45, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g46, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g67, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g68, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g69, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g57, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g58, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g59, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(g47, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g48, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(g49, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g94, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g95, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g96, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g84, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g85, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g86, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g74, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g75, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g76, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g87, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g88, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g89, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g97, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g98, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g99, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(g77, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g78, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(g79, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitbtn)
                    .addComponent(solvebtn))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {clearbtn, exitbtn, solvebtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {g17, g18});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g28, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g37, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g38, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g39, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g34, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g35, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g36, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g41, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g42, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g43, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g51, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g52, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g53, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g61, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g62, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g63, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g44, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g45, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g46, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g54, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g55, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g56, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g64, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g65, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g66, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g71, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g72, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g73, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g81, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g82, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g83, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g91, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g92, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g93, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g74, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g75, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g76, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g84, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g85, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g86, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g94, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g95, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g96, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g77, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g78, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g79, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g87, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g88, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g89, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(g97, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g98, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g99, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g47, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g48, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g49, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(g57, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g58, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(g59, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(g67, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(g68, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(g69, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(solvebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitbtn)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {clearbtn, exitbtn, solvebtn});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {g17, g18});

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    //Sudoku sdku = new Sudoku();
    
    private void acquiregrid()
    {
       String s;
       /* 
       /*Row 1
       */
       {
        s=g11.getText();
        if(s.equals("")) grid[0][0] = 0;
        else grid[0][0] = Integer.parseInt(s);
        
        s=g12.getText();
        if(s.equals("")) grid[0][1] = 0;
        else grid[0][1] = Integer.parseInt(s);
        
        s=g13.getText();
        if(s.equals("")) grid[0][2] = 0;
        else grid[0][2] = Integer.parseInt(s);
        
        s=g14.getText();
        if(s.equals("")) grid[0][3] = 0;
        else grid[0][3] = Integer.parseInt(s);
        
        s=g15.getText();
        if(s.equals("")) grid[0][4] = 0;
        else grid[0][4] = Integer.parseInt(s);
        
        s=g16.getText();
        if(s.equals("")) grid[0][5] = 0;
        else grid[0][5] = Integer.parseInt(s);
        
        s=g17.getText();
        if(s.equals("")) grid[0][6] = 0;
        else grid[0][6] = Integer.parseInt(s);
        
        s=g18.getText();
        if(s.equals("")) grid[0][7] = 0;
        else grid[0][7] = Integer.parseInt(s);
        
        s=g19.getText();
        if(s.equals("")) grid[0][8] = 0;
        else grid[0][8] = Integer.parseInt(s);
       }
        /*
        /* Row 2
        */
        
        s=g21.getText();
        if(s.equals("")) grid[1][0] = 0;
        else grid[1][0] = Integer.parseInt(s);
        
        s=g22.getText();
        if(s.equals("")) grid[1][1] = 0;
        else grid[1][1] = Integer.parseInt(s);
        
        s=g23.getText();
        if(s.equals("")) grid[1][2] = 0;
        else grid[1][2] = Integer.parseInt(s);
        
        s=g24.getText();
        if(s.equals("")) grid[1][3] = 0;
        else grid[1][3] = Integer.parseInt(s);
        
        s=g25.getText();
        if(s.equals("")) grid[1][4] = 0;
        else grid[1][4] = Integer.parseInt(s);
        
        s=g26.getText();
        if(s.equals("")) grid[1][5] = 0;
        else grid[1][5] = Integer.parseInt(s);
        
        s=g27.getText();
        if(s.equals("")) grid[1][6] = 0;
        else grid[1][6] = Integer.parseInt(s);
        
        s=g28.getText();
        if(s.equals("")) grid[1][7] = 0;
        else grid[1][7] = Integer.parseInt(s);
        
        s=g29.getText();
        if(s.equals("")) grid[1][8] = 0;
        else grid[1][8] = Integer.parseInt(s);
        
        /*
        /* Row 3
        */
        s=g31.getText();
        if(s.equals("")) grid[2][0] = 0;
        else grid[2][0] = Integer.parseInt(s);
        
        s=g32.getText();
        if(s.equals("")) grid[2][1] = 0;
        else grid[2][1] = Integer.parseInt(s);
        
        s=g33.getText();
        if(s.equals("")) grid[2][2] = 0;
        else grid[2][2] = Integer.parseInt(s);
        
        s=g34.getText();
        if(s.equals("")) grid[2][3] = 0;
        else grid[2][3] = Integer.parseInt(s);
        
        s=g35.getText();
        if(s.equals("")) grid[2][4] = 0;
        else grid[2][4] = Integer.parseInt(s);
        
        s=g36.getText();
        if(s.equals("")) grid[2][5] = 0;
        else grid[2][5] = Integer.parseInt(s);
        
        s=g37.getText();
        if(s.equals("")) grid[2][6] = 0;
        else grid[2][6] = Integer.parseInt(s);
        
        s=g38.getText();
        if(s.equals("")) grid[2][7] = 0;
        else grid[2][7] = Integer.parseInt(s);
        
        s=g39.getText();
        if(s.equals("")) grid[2][8] = 0;
        else grid[2][8] = Integer.parseInt(s);
        
        /*
        /* Row 4
        */
        s=g41.getText();
        if(s.equals("")) grid[3][0] = 0;
        else grid[3][0] = Integer.parseInt(s);
        
        s=g42.getText();
        if(s.equals("")) grid[3][1] = 0;
        else grid[3][1] = Integer.parseInt(s);
        
        s=g43.getText();
        if(s.equals("")) grid[3][2] = 0;
        else grid[3][2] = Integer.parseInt(s);
        
        s=g44.getText();
        if(s.equals("")) grid[3][3] = 0;
        else grid[3][3] = Integer.parseInt(s);
        
        s=g45.getText();
        if(s.equals("")) grid[3][4] = 0;
        else grid[3][4] = Integer.parseInt(s);
        
        s=g46.getText();
        if(s.equals("")) grid[3][5] = 0;
        else grid[3][5] = Integer.parseInt(s);
        
        s=g47.getText();
        if(s.equals("")) grid[3][6] = 0;
        else grid[3][6] = Integer.parseInt(s);
        
        s=g48.getText();
        if(s.equals("")) grid[3][7] = 0;
        else grid[3][7] = Integer.parseInt(s);
        
        s=g49.getText();
        if(s.equals("")) grid[3][8] = 0;
        else grid[3][8] = Integer.parseInt(s);
        
        /*
        /* Row 5
        */
        s=g51.getText();
        if(s.equals("")) grid[4][0] = 0;
        else grid[4][0] = Integer.parseInt(s);
        
        s=g52.getText();
        if(s.equals("")) grid[4][1] = 0;
        else grid[4][1] = Integer.parseInt(s);
        
        s=g53.getText();
        if(s.equals("")) grid[4][2] = 0;
        else grid[4][2] = Integer.parseInt(s);
        
        s=g54.getText();
        if(s.equals("")) grid[4][3] = 0;
        else grid[4][3] = Integer.parseInt(s);
        
        s=g55.getText();
        if(s.equals("")) grid[4][4] = 0;
        else grid[4][4] = Integer.parseInt(s);
        
        s=g56.getText();
        if(s.equals("")) grid[4][5] = 0;
        else grid[4][5] = Integer.parseInt(s);
        
        s=g57.getText();
        if(s.equals("")) grid[4][6] = 0;
        else grid[4][6] = Integer.parseInt(s);
        
        s=g58.getText();
        if(s.equals("")) grid[4][7] = 0;
        else grid[4][7] = Integer.parseInt(s);
        
        s=g59.getText();
        if(s.equals("")) grid[4][8] = 0;
        else grid[4][8] = Integer.parseInt(s);
        
        /*
        /* Row 6
        */
        s=g61.getText();
        if(s.equals("")) grid[5][0] = 0;
        else grid[5][0] = Integer.parseInt(s);
        
        s=g62.getText();
        if(s.equals("")) grid[5][1] = 0;
        else grid[5][1] = Integer.parseInt(s);
        
        s=g63.getText();
        if(s.equals("")) grid[5][2] = 0;
        else grid[5][2] = Integer.parseInt(s);
        
        s=g64.getText();
        if(s.equals("")) grid[5][3] = 0;
        else grid[5][3] = Integer.parseInt(s);
        
        s=g65.getText();
        if(s.equals("")) grid[5][4] = 0;
        else grid[5][4] = Integer.parseInt(s);
        
        s=g66.getText();
        if(s.equals("")) grid[5][5] = 0;
        else grid[5][5] = Integer.parseInt(s);
        
        s=g67.getText();
        if(s.equals("")) grid[5][6] = 0;
        else grid[5][6] = Integer.parseInt(s);
        
        s=g68.getText();
        if(s.equals("")) grid[5][7] = 0;
        else grid[5][7] = Integer.parseInt(s);
        
        s=g69.getText();
        if(s.equals("")) grid[5][8] = 0;
        else grid[5][8] = Integer.parseInt(s);
        
        /*
        /* Row 7 
        */
        s=g71.getText();
        if(s.equals("")) grid[6][0] = 0;
        else grid[6][0] = Integer.parseInt(s);
        
        s=g72.getText();
        if(s.equals("")) grid[6][1] = 0;
        else grid[6][1] = Integer.parseInt(s);
        
        s=g73.getText();
        if(s.equals("")) grid[6][2] = 0;
        else grid[6][2] = Integer.parseInt(s);
        
        s=g74.getText();
        if(s.equals("")) grid[6][3] = 0;
        else grid[6][3] = Integer.parseInt(s);
        
        s=g75.getText();
        if(s.equals("")) grid[6][4] = 0;
        else grid[6][4] = Integer.parseInt(s);
        
        s=g76.getText();
        if(s.equals("")) grid[6][5] = 0;
        else grid[6][5] = Integer.parseInt(s);
        
        s=g77.getText();
        if(s.equals("")) grid[6][6] = 0;
        else grid[6][6] = Integer.parseInt(s);
        
        s=g78.getText();
        if(s.equals("")) grid[6][7] = 0;
        else grid[6][7] = Integer.parseInt(s);
        
        s=g79.getText();
        if(s.equals("")) grid[6][8] = 0;
        else grid[6][8] = Integer.parseInt(s);
        
        /*
        /* Row 8
        */
        s=g81.getText();
        if(s.equals("")) grid[7][0] = 0;
        else grid[7][0] = Integer.parseInt(s);
        
        s=g82.getText();
        if(s.equals("")) grid[7][1] = 0;
        else grid[7][1] = Integer.parseInt(s);
        
        s=g83.getText();
        if(s.equals("")) grid[7][2] = 0;
        else grid[7][2] = Integer.parseInt(s);
        
        s=g84.getText();
        if(s.equals("")) grid[7][3] = 0;
        else grid[7][3] = Integer.parseInt(s);
        
        s=g85.getText();
        if(s.equals("")) grid[7][4] = 0;
        else grid[7][4] = Integer.parseInt(s);
        
        s=g86.getText();
        if(s.equals("")) grid[7][5] = 0;
        else grid[7][5] = Integer.parseInt(s);
        
        s=g87.getText();
        if(s.equals("")) grid[7][6] = 0;
        else grid[7][6] = Integer.parseInt(s);
        
        s=g88.getText();
        if(s.equals("")) grid[7][7] = 0;
        else grid[7][7] = Integer.parseInt(s);
        
        s=g89.getText();
        if(s.equals("")) grid[7][8] = 0;
        else grid[7][8] = Integer.parseInt(s);
        
        /*
        /* Row 9
        */
        s=g91.getText();
        if(s.equals("")) grid[8][0] = 0;
        else grid[8][0] = Integer.parseInt(s);
        
        s=g92.getText();
        if(s.equals("")) grid[8][1] = 0;
        else grid[8][1] = Integer.parseInt(s);
        
        s=g93.getText();
        if(s.equals("")) grid[8][2] = 0;
        else grid[8][2] = Integer.parseInt(s);
        
        s=g94.getText();
        if(s.equals("")) grid[8][3] = 0;
        else grid[8][3] = Integer.parseInt(s);
        
        s=g95.getText();
        if(s.equals("")) grid[8][4] = 0;
        else grid[8][4] = Integer.parseInt(s);
        
        s=g96.getText();
        if(s.equals("")) grid[8][5] = 0;
        else grid[8][5] = Integer.parseInt(s);
        
        s=g97.getText();
        if(s.equals("")) grid[8][6] = 0;
        else grid[8][6] = Integer.parseInt(s);
        
        s=g98.getText();
        if(s.equals("")) grid[8][7] = 0;
        else grid[8][7] = Integer.parseInt(s);
        
        s=g99.getText();
        if(s.equals("")) grid[8][8] = 0;
        else grid[8][8] = Integer.parseInt(s);
        
        // End Of Grid Acquire Function //
    }
    
    private void showans()
    {
        g11.setText(String.valueOf(g1.ansgrid[0][0]));
        g12.setText(String.valueOf(g1.ansgrid[0][1]));
        g13.setText(String.valueOf(g1.ansgrid[0][2]));
        g14.setText(String.valueOf(g1.ansgrid[0][3]));
        g15.setText(String.valueOf(g1.ansgrid[0][4]));
        g16.setText(String.valueOf(g1.ansgrid[0][5]));
        g17.setText(String.valueOf(g1.ansgrid[0][6]));
        g18.setText(String.valueOf(g1.ansgrid[0][7]));
        g19.setText(String.valueOf(g1.ansgrid[0][8]));
        g21.setText(String.valueOf(g1.ansgrid[1][0]));
        g22.setText(String.valueOf(g1.ansgrid[1][1]));
        g23.setText(String.valueOf(g1.ansgrid[1][2]));
        g24.setText(String.valueOf(g1.ansgrid[1][3]));
        g25.setText(String.valueOf(g1.ansgrid[1][4]));
        g26.setText(String.valueOf(g1.ansgrid[1][5]));
        g27.setText(String.valueOf(g1.ansgrid[1][6]));
        g28.setText(String.valueOf(g1.ansgrid[1][7]));
        g29.setText(String.valueOf(g1.ansgrid[1][8]));
        g31.setText(String.valueOf(g1.ansgrid[2][0]));
        g32.setText(String.valueOf(g1.ansgrid[2][1]));
        g33.setText(String.valueOf(g1.ansgrid[2][2]));
        g34.setText(String.valueOf(g1.ansgrid[2][3]));
        g35.setText(String.valueOf(g1.ansgrid[2][4]));
        g36.setText(String.valueOf(g1.ansgrid[2][5]));
        g37.setText(String.valueOf(g1.ansgrid[2][6]));
        g38.setText(String.valueOf(g1.ansgrid[2][7]));
        g39.setText(String.valueOf(g1.ansgrid[2][8]));
        g41.setText(String.valueOf(g1.ansgrid[3][0]));
        g42.setText(String.valueOf(g1.ansgrid[3][1]));
        g43.setText(String.valueOf(g1.ansgrid[3][2]));
        g44.setText(String.valueOf(g1.ansgrid[3][3]));
        g45.setText(String.valueOf(g1.ansgrid[3][4]));
        g46.setText(String.valueOf(g1.ansgrid[3][5]));
        g47.setText(String.valueOf(g1.ansgrid[3][6]));
        g48.setText(String.valueOf(g1.ansgrid[3][7]));
        g49.setText(String.valueOf(g1.ansgrid[3][8]));
        g51.setText(String.valueOf(g1.ansgrid[4][0]));
        g52.setText(String.valueOf(g1.ansgrid[4][1]));
        g53.setText(String.valueOf(g1.ansgrid[4][2]));
        g54.setText(String.valueOf(g1.ansgrid[4][3]));
        g55.setText(String.valueOf(g1.ansgrid[4][4]));
        g56.setText(String.valueOf(g1.ansgrid[4][5]));
        g57.setText(String.valueOf(g1.ansgrid[4][6]));
        g58.setText(String.valueOf(g1.ansgrid[4][7]));
        g59.setText(String.valueOf(g1.ansgrid[4][8]));
        g61.setText(String.valueOf(g1.ansgrid[5][0]));
        g62.setText(String.valueOf(g1.ansgrid[5][1]));
        g63.setText(String.valueOf(g1.ansgrid[5][2]));
        g64.setText(String.valueOf(g1.ansgrid[5][3]));
        g65.setText(String.valueOf(g1.ansgrid[5][4]));
        g66.setText(String.valueOf(g1.ansgrid[5][5]));
        g67.setText(String.valueOf(g1.ansgrid[5][6]));
        g68.setText(String.valueOf(g1.ansgrid[5][7]));
        g69.setText(String.valueOf(g1.ansgrid[5][8]));
        g71.setText(String.valueOf(g1.ansgrid[6][0]));
        g72.setText(String.valueOf(g1.ansgrid[6][1]));
        g73.setText(String.valueOf(g1.ansgrid[6][2]));
        g74.setText(String.valueOf(g1.ansgrid[6][3]));
        g75.setText(String.valueOf(g1.ansgrid[6][4]));
        g76.setText(String.valueOf(g1.ansgrid[6][5]));
        g77.setText(String.valueOf(g1.ansgrid[6][6]));
        g78.setText(String.valueOf(g1.ansgrid[6][7]));
        g79.setText(String.valueOf(g1.ansgrid[6][8]));
        g81.setText(String.valueOf(g1.ansgrid[7][0]));
        g82.setText(String.valueOf(g1.ansgrid[7][1]));
        g83.setText(String.valueOf(g1.ansgrid[7][2]));
        g84.setText(String.valueOf(g1.ansgrid[7][3]));
        g85.setText(String.valueOf(g1.ansgrid[7][4]));
        g86.setText(String.valueOf(g1.ansgrid[7][5]));
        g87.setText(String.valueOf(g1.ansgrid[7][6]));
        g88.setText(String.valueOf(g1.ansgrid[7][7]));
        g89.setText(String.valueOf(g1.ansgrid[7][8]));
        g91.setText(String.valueOf(g1.ansgrid[8][0]));
        g92.setText(String.valueOf(g1.ansgrid[8][1]));
        g93.setText(String.valueOf(g1.ansgrid[8][2]));
        g94.setText(String.valueOf(g1.ansgrid[8][3]));
        g95.setText(String.valueOf(g1.ansgrid[8][4]));
        g96.setText(String.valueOf(g1.ansgrid[8][5]));
        g97.setText(String.valueOf(g1.ansgrid[8][6]));
        g98.setText(String.valueOf(g1.ansgrid[8][7]));
        g99.setText(String.valueOf(g1.ansgrid[8][8]));

    }
    
    private void transfergrid()
    {
        int i,j;        
        for(i=0;i<9;i++)
            for(j=0;j<9;j++)
            {
                g1.ansgrid[i][j] = grid[i][j];
            }
    }
    
    public void clearall()
    {
        g11.setText("");
        g12.setText("");
        g13.setText("");
        g14.setText("");
        g15.setText("");
        g16.setText("");
        g17.setText("");
        g18.setText("");
        g19.setText("");
        g21.setText("");
        g22.setText("");
        g23.setText("");
        g24.setText("");
        g25.setText("");
        g26.setText("");
        g27.setText("");
        g28.setText("");
        g29.setText("");
        g31.setText("");
        g32.setText("");
        g33.setText("");
        g34.setText("");
        g35.setText("");
        g36.setText("");
        g37.setText("");
        g38.setText("");
        g39.setText("");
        g41.setText("");
        g42.setText("");
        g43.setText("");
        g44.setText("");
        g45.setText("");
        g46.setText("");
        g47.setText("");
        g48.setText("");
        g49.setText("");
        g51.setText("");
        g52.setText("");
        g53.setText("");
        g54.setText("");
        g55.setText("");
        g56.setText("");
        g57.setText("");
        g58.setText("");
        g59.setText("");
        g61.setText("");
        g62.setText("");
        g63.setText("");
        g64.setText("");
        g65.setText("");
        g66.setText("");
        g67.setText("");
        g68.setText("");
        g69.setText("");
        g71.setText("");
        g72.setText("");
        g73.setText("");
        g74.setText("");
        g75.setText("");
        g76.setText("");
        g77.setText("");
        g78.setText("");
        g79.setText("");
        g81.setText("");
        g82.setText("");
        g83.setText("");
        g84.setText("");
        g85.setText("");
        g86.setText("");
        g87.setText("");
        g88.setText("");
        g89.setText("");
        g91.setText("");
        g92.setText("");
        g93.setText("");
        g94.setText("");
        g95.setText("");
        g96.setText("");
        g99.setText("");
        g97.setText("");
        g98.setText("");
    }
    
    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        ClearConf clr = new ClearConf();
        if(clr.showconf()==true)
            clearall();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        ExitConf.showhidconf(1);
        //exitfn();howhidconf(1);
        
    }//GEN-LAST:event_exitbtnActionPerformed

    private void g26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g26ActionPerformed

    private void g35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g35ActionPerformed

    private void solvebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solvebtnActionPerformed
        
        acquiregrid();
        boolean gd = Sudoku.checkall(grid);
        
        if(gd == false)
        {
            InvalidInp.main(1);
        }
        else
        {
            transfergrid();
            boolean gd2 = Sudoku.solve(g1);
            if(gd2 == true)
            showans();
            
            else 
                ;
        }
        
        
    }//GEN-LAST:event_solvebtnActionPerformed

    private void g99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g99ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_g99ActionPerformed

    public static void exitfn()
    {
        exit(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        //GridClass g1 = new GridClass();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Solver panel = new Solver();
                panel.setVisible(true);
                panel.setResizable(false);
                panel.setLocation(300,100);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField g11;
    private javax.swing.JTextField g12;
    private javax.swing.JTextField g13;
    private javax.swing.JTextField g14;
    private javax.swing.JTextField g15;
    private javax.swing.JTextField g16;
    private javax.swing.JTextField g17;
    private javax.swing.JTextField g18;
    private javax.swing.JTextField g19;
    private javax.swing.JTextField g21;
    private javax.swing.JTextField g22;
    private javax.swing.JTextField g23;
    private javax.swing.JTextField g24;
    private javax.swing.JTextField g25;
    private javax.swing.JTextField g26;
    private javax.swing.JTextField g27;
    private javax.swing.JTextField g28;
    private javax.swing.JTextField g29;
    private javax.swing.JTextField g31;
    private javax.swing.JTextField g32;
    private javax.swing.JTextField g33;
    private javax.swing.JTextField g34;
    private javax.swing.JTextField g35;
    private javax.swing.JTextField g36;
    private javax.swing.JTextField g37;
    private javax.swing.JTextField g38;
    private javax.swing.JTextField g39;
    private javax.swing.JTextField g41;
    private javax.swing.JTextField g42;
    private javax.swing.JTextField g43;
    private javax.swing.JTextField g44;
    private javax.swing.JTextField g45;
    private javax.swing.JTextField g46;
    private javax.swing.JTextField g47;
    private javax.swing.JTextField g48;
    private javax.swing.JTextField g49;
    private javax.swing.JTextField g51;
    private javax.swing.JTextField g52;
    private javax.swing.JTextField g53;
    private javax.swing.JTextField g54;
    private javax.swing.JTextField g55;
    private javax.swing.JTextField g56;
    private javax.swing.JTextField g57;
    private javax.swing.JTextField g58;
    private javax.swing.JTextField g59;
    private javax.swing.JTextField g61;
    private javax.swing.JTextField g62;
    private javax.swing.JTextField g63;
    private javax.swing.JTextField g64;
    private javax.swing.JTextField g65;
    private javax.swing.JTextField g66;
    private javax.swing.JTextField g67;
    private javax.swing.JTextField g68;
    private javax.swing.JTextField g69;
    private javax.swing.JTextField g71;
    private javax.swing.JTextField g72;
    private javax.swing.JTextField g73;
    private javax.swing.JTextField g74;
    private javax.swing.JTextField g75;
    private javax.swing.JTextField g76;
    private javax.swing.JTextField g77;
    private javax.swing.JTextField g78;
    private javax.swing.JTextField g79;
    private javax.swing.JTextField g81;
    private javax.swing.JTextField g82;
    private javax.swing.JTextField g83;
    private javax.swing.JTextField g84;
    private javax.swing.JTextField g85;
    private javax.swing.JTextField g86;
    private javax.swing.JTextField g87;
    private javax.swing.JTextField g88;
    private javax.swing.JTextField g89;
    private javax.swing.JTextField g91;
    private javax.swing.JTextField g92;
    private javax.swing.JTextField g93;
    private javax.swing.JTextField g94;
    private javax.swing.JTextField g95;
    private javax.swing.JTextField g96;
    private javax.swing.JTextField g97;
    private javax.swing.JTextField g98;
    private javax.swing.JTextField g99;
    private javax.swing.JButton solvebtn;
    // End of variables declaration//GEN-END:variables
}
